/* Danish → English dictionary. Danish is the source language of the app, so
   the Danish string is the lookup key; a missing entry falls back to Danish.
   Use {name} placeholders for interpolation via t(str, { name }). */

export const EN: Record<string, string> = {
  // ── Navigation ──────────────────────────────────────────────────────
  'Hjem': 'Home',
  'Ava': 'Ava',
  'Inspiration': 'Inspiration',
  'Venues': 'Venues',
  'Leverandører': 'Vendors',
  'Henvendelser': 'Inbox',
  'Budget': 'Budget',
  'Gæster': 'Guests',
  'Hjemmeside': 'Website',
  'Invitationer': 'Invitations',
  'Tidslinje': 'Timeline',
  'Bordplan': 'Seating',
  'Alle sider': 'All pages',
  'Flere sider': 'More pages',
  'Indstillinger': 'Settings',
  'Luk': 'Close',

  // ── Common verbs / chrome ───────────────────────────────────────────
  'Tilbage': 'Back',
  'Næste': 'Next',
  'Videre': 'Continue',
  'Gem': 'Save',
  'Gemt': 'Saved',
  'Annuller': 'Cancel',
  'Tilføj': 'Add',
  'Fjern': 'Remove',
  'Slet': 'Delete',
  'Send': 'Send',
  'Sendt': 'Sent',
  'Godkend & send': 'Approve & send',
  'Afvis': 'Dismiss',
  'Generér igen': 'Regenerate',
  'Importér': 'Import',
  'Tal med Ava': 'Talk to Ava',
  'Spørg Ava': 'Ask Ava',
  'Se venues der matcher': 'See matching venues',
  'kommer snart': 'coming soon',
  'Sprog': 'Language',
  'Dansk': 'Danish',
  'Engelsk': 'English',

  // ── Onboarding ──────────────────────────────────────────────────────
  'Hej! Jeg er Ava — din personlige bryllupsassistent. Lad os starte med det vigtigste: hvem er I, og hvornår er den store dag?':
    "Hi! I'm Ava — your personal wedding assistant. Let's start with the essentials: who are you, and when is the big day?",
  'Planlagt med ro — af Ava, godkendt af jer.': 'Planned calmly — by Ava, approved by you.',
  'Fortæl om': 'Tell us about the',
  'brylluppet': 'wedding',
  'Ingen konto nødvendig — I kan altid ændre det undervejs.': 'No account needed — you can always change it later.',
  'Dit navn': 'Your name',
  'Partners navn': "Partner's name",
  'Fornavn': 'First name',
  'Lokation': 'Location',
  'Hjemland eller udland — skriv hvad I drømmer om.': 'Home or abroad — write whatever you dream of.',
  'f.eks. nær København · Toscana · Sydfrankrig': 'e.g. near Copenhagen · Tuscany · South of France',
  'Hvornår?': 'When?',
  'En sæson er fint — I behøver ikke en præcis dato endnu.': "A season is fine — you don't need an exact date yet.",
  'Præcis dato': 'Exact date',
  'Ved ikke endnu': 'Not sure yet',
  'Det lyder godt': 'Sounds good',
  'Hvor stort': 'How big are',
  'tænker I?': 'you thinking?',
  'Bare et pejlemærke — Ava bruger det til at forme venues, budget og tidslinje.':
    'Just a ballpark — Ava uses it to shape venues, budget and timeline.',
  'Antal gæster': 'Number of guests',
  'Valgfrit — hjælper Ava med at fordele pengene fornuftigt.': 'Optional — helps Ava split the money sensibly.',
  'Kun os to': 'Just us two',
  'Under 50': 'Under 50',
  'Nøjsomt': 'Lean',
  'Mellemklasse': 'Mid-range',
  'Rundhåndet': 'Generous',
  'Himlen er grænsen': "Sky's the limit",
  'Vil helst ikke sige': 'Rather not say',
  'Jeres drømmebyllup': 'Your dream wedding',
  'Vælg de stemninger der rammer jer — og beskriv gerne med egne ord. Ava bruger det til briefs og stil.':
    'Pick the moods that fit you — and describe it in your own words. Ava uses it for briefs and style.',
  'Stemning': 'Mood',
  'Vælg gerne flere.': 'Pick as many as you like.',
  'Med egne ord': 'In your own words',
  'Have': 'Garden',
  'Rustik lade': 'Rustic barn',
  'Moderne loft': 'Modern loft',
  'Klassisk balsal': 'Classic ballroom',
  'Strand': 'Beach',
  'Slot / herregård': 'Castle / manor',
  'Intimt': 'Intimate',
  'Boho': 'Boho',
  'Destination': 'Destination',
  'Vi drømmer om et bryllup i en gammel avlsgård med lange borde, levende lys og en varm, afslappet stemning…':
    'We dream of a wedding in an old farmhouse with long tables, candlelight and a warm, relaxed atmosphere…',
  'Giv {name} adgang': 'Give {name} access',
  'din partner': 'your partner',
  'I deler samme plan — ingen duplikerede lister eller beskedkopiering.':
    'You share one plan — no duplicate lists or copy-pasting.',
  '{name}s e-mail': "{name}'s email",
  'Invitation sendt til {email}. {name} får et link til at oprette adgang.':
    'Invitation sent to {email}. {name} gets a link to create access.',
  'eller': 'or',
  'Spring over — invitér {name} senere': 'Skip — invite {name} later',
  'Se jeres plan': 'See your plan',
  'Ava · Arbejdede imens I svarede': 'Ava · Worked while you answered',
  'Jeg har forberedt': "I've prepared",
  'tre ting til jer.': 'three things for you.',
  'Baseret på {guests} gæster nær {location} og jeres stil. Ét klik for at se det hele.':
    'Based on {guests} guests near {location} and your style. One click to see it all.',
  'Tidslinje med {n} milepæle': 'Timeline with {n} milestones',
  'Forankret baglæns fra {date}': 'Anchored backwards from {date}',
  '3 venues fundet nær {location}': '3 venues found near {location}',
  'Matchet på gæstetal, stil og dato': 'Matched on guest count, style and date',
  'Ava har skrevet · Venue-henvendelse': 'Ava wrote · Venue enquiry',
  'Klar til send': 'Ready to send',
  'Til': 'To',
  'Emne': 'Subject',
  'Forespørgsel — bryllup {date}': 'Enquiry — wedding {date}',
  'Gå ind i Kalas': 'Enter Kalas',
  'Se hvad Ava har forberedt': "See what Ava's prepared",
  'Gratis at udforske · I godkender alt før noget sendes':
    'Free to explore · You approve everything before anything is sent',
  'snart': 'soon',
};
