/* Danish → English dictionary. Danish is the source language of the app, so
   the Danish string is the lookup key; a missing entry falls back to Danish.
   Use {name} placeholders for interpolation via t(str, { name }). */

export const EN: Record<string, string> = {
  // ── Navigation ──────────────────────────────────────────────────────
  'Hjem': 'Home',
  'Ava': 'Ava',
  'Venue & leverandører': 'Venue & vendors',
  'Explore': 'Explore',
  'Shortlist': 'Shortlist',
  'Inbox': 'Inbox',
  'Booked': 'Booked',
  'Find venues, leverandører, tilbud…': 'Find venues, vendors, quotes…',
  'Fra opdagelse til henvendelser og booking — ét samlet overblik over jeres bryllupsteam.': 'From discovery to outreach and booking — one unified view of your wedding team.',
  'Alle': 'All',
  'Venue': 'Venue',
  'Foto': 'Photo',
  'Blomster': 'Flowers',
  'Catering': 'Catering',
  'Bar & Drinks': 'Bar & Drinks',
  'Bryllupskage': 'Wedding cake',
  'Musik': 'Music',
  'Beauty': 'Beauty',
  'Samlet budget': 'Total budget',
  'Budget': 'Budget',
  'Gæster': 'Guests',
  'Hjemmeside': 'Website',
  'Ønskeliste': 'Registry',
  'Invitationer': 'Invitations',
  'Tidslinje': 'Timeline',
  'Bordplan': 'Seating',
  'Alle sider': 'All pages',
  'Flere sider': 'More pages',
  'Indstillinger': 'Settings',
  'Luk': 'Close',
  'Skjul menu': 'Collapse menu',
  'Vis menu': 'Expand menu',
  'Planlægning': 'Planning',
  '{n} dage tilbage': '{n} days remaining',
  'Tal med Ava — {n} nye beskeder': 'Talk to Ava — {n} new messages',

  // ── Home dashboard (palette refresh) ────────────────────────────────
  'Planlægningshjem': 'Planning home',
  'Brylluppet for': 'The wedding of',
  'Angiv dato og budget': 'Set your wedding date & budget',
  'Shortlist jeres venues': 'Shortlist your top venues',
  'Lav gæstelisten': 'Draft your guest list',
  'Book jeres leverandører': 'Book your key vendors',
  'Send save the dates': 'Send your save the dates',
  '{done} af {total} klaret': '{done} of {total} done',
  'De første skridt for at sætte planlægningen i gang.': 'A few first steps to get your planning moving.',
  'Færdig': 'Completed',
  'Mangler': 'To do',
  'Find jeres venue': 'Find your venue',
  'Steder der matcher gæsteantal, stemning, placering og budget.': 'Places matched to your guest count, atmosphere, location and budget.',
  'Udforsk venues': 'Browse venues',
  'Find leverandører': 'Find vendors',
  'Saml holdet der bringer dagen til live.': 'Build the team that brings the day to life.',
  'Se alle →': 'See all →',
  '{n} fundet': '{n} found',
  'Florister i nærheden': 'Florists nearby',
  "DJ's og bands": 'DJs and bands',
  'Fotografer': 'Photographers',
  'Menuer og kage': 'Menus and cake',
  'Over hele planlægningen': 'Across your planning',
  'Et roligt overblik over alle hjørner af brylluppet.': 'A calm look into every corner of the wedding.',
  'kr {spent} af kr {total} fordelt': 'kr {spent} of kr {total} committed',
  'Angiv budget for at se fordeling': 'Set a budget to see allocation',
  'Åbn budget →': 'Open budget →',
  '{confirmed} bekræftet · {missing} mangler kontakt': '{confirmed} confirmed · {missing} addresses missing',
  'Tilføj jeres første gæster': 'Add your first guests',
  'Åbn gæster →': 'Open guests →',
  'på shortlisten til gennemgang': 'shortlisted for review',
  'Start med at udforske steder': 'Start exploring venues',
  'Åbn venues →': 'Open venues →',
  'Kladde': 'Draft',
  'Jeres bryllupsside er publiceret': 'Your wedding site is published',
  'Vælg et tema og publicér': 'Choose a theme and publish',
  'Åbn hjemmeside →': 'Open website →',
  'Planlagt med omtanke af {names}, guidet af Ava.': 'Planned with care by {names}, guided by Ava.',
  'Live': 'Live',

  // ── Home dashboard (command center) ─────────────────────────────────
  'Bryllups command center': 'Wedding command center',
  'Til den store dag': 'Until the big day',
  'dage': 'days',
  'Planlægningsfremdrift': 'Planning progress',
  'På sporet': 'On track',
  'Kom godt i gang': 'Getting started',
  '{done} af {total} opgaver færdige': '{done} of {total} tasks complete',
  'Tidslinjen sættes op automatisk': 'Timeline will populate automatically',
  'Se tidslinje': 'View timeline',
  'Næste milepæl': 'Next milestone',
  'I gang': 'In progress',
  'Planlæg med Ava': 'Plan with Ava',
  'Åbn tidslinje': 'Open timeline',
  'Jeres vej til brylluppet': 'Your path to the wedding',
  'De næste vigtige øjeblikke, i rækkefølge.': 'The next key moments, in order.',
  'Fuld tidslinje': 'Full timeline',
  'Godkendelseskø': 'Approval queue',
  'Jeres beslutninger holder planlægningen i gang.': 'Your decisions keep planning moving.',
  'Ingen afventende beslutninger — nyd roen.': 'No pending decisions — enjoy the calm.',
  'Ca. {n} min at klare': 'About {n} minutes to clear',
  'Gennemgå alle': 'Review all',
  '{n} beslutninger venter på jer. Resten bevæger sig fremad.': '{n} decisions need you. Everything else is moving forward.',
  'Vælg mellem {n} forslag': 'Choose between {n} proposals',
  'Ava har sammenlignet pris, kapacitet og rejsetid': 'Ava compared price, capacity and travel',
  'Godkend svar til {name}': 'Approve reply to {name}',
  'Ava har skrevet et svar klar til jer': 'Ava has a reply ready for you',
  'Gennemgå {n} manglende kontakter': 'Review {n} missing contacts',
  'Invitationer er blokeret indtil listen er komplet': 'Invitations are blocked until the list is complete',
  'Færdig': 'Done',
  'Milepæl': 'Milestone',
  'Notifikationer': 'Notifications',
  'I dag': 'Today',

  // ── Common verbs / chrome ───────────────────────────────────────────
  'Tilbage': 'Back',
  'Næste': 'Next',
  'Videre': 'Continue',
  'Gem': 'Save',
  'Gemt': 'Saved',
  'Annuller': 'Cancel',
  'Tilføj': 'Add',
  'Fjern': 'Remove',
  'Slet': 'Delete',
  'Send': 'Send',
  'Sendt': 'Sent',
  'Godkend & send': 'Approve & send',
  'Afvis': 'Dismiss',
  'Generér igen': 'Regenerate',
  'Importér': 'Import',
  'Tal med Ava': 'Talk to Ava',
  'Spørg Ava': 'Ask Ava',
  'Se venues der matcher': 'See matching venues',
  'kommer snart': 'coming soon',
  'Sprog': 'Language',
  'Dansk': 'Danish',
  'Engelsk': 'English',

  // ── Onboarding ──────────────────────────────────────────────────────
  'Hej! Jeg er Ava — din personlige bryllupsassistent. Lad os starte med det vigtigste: hvem er I, og hvornår er den store dag?':
    "Hi! I'm Ava — your personal wedding assistant. Let's start with the essentials: who are you, and when is the big day?",
  'Planlagt med ro — af Ava, godkendt af jer.': 'Planned calmly — by Ava, approved by you.',
  'Fortæl om': 'Tell us about the',
  'brylluppet': 'wedding',
  'Ingen konto nødvendig — I kan altid ændre det undervejs.': 'No account needed — you can always change it later.',
  'Dit navn': 'Your name',
  'Partners navn': "Partner's name",
  'Fornavn': 'First name',
  'Lokation': 'Location',
  'Hjemland eller udland — skriv hvad I drømmer om.': 'Home or abroad — write whatever you dream of.',
  'f.eks. nær København · Toscana · Sydfrankrig': 'e.g. near Copenhagen · Tuscany · South of France',
  'Hvornår?': 'When?',
  'En sæson er fint — I behøver ikke en præcis dato endnu.': "A season is fine — you don't need an exact date yet.",
  'Præcis dato': 'Exact date',
  'Vi ved den allerede': 'We already know',
  'Vælg jeres dato': 'Pick your date',
  'Ved ikke endnu': 'Not sure yet',
  'Det lyder godt': 'Sounds good',
  'Hvor stort': 'How big are',
  'tænker I?': 'you thinking?',
  'Bare et pejlemærke — Ava bruger det til at forme venues, budget og tidslinje.':
    'Just a ballpark — Ava uses it to shape venues, budget and timeline.',
  'Antal gæster': 'Number of guests',
  'Valgfrit — hjælper Ava med at fordele pengene fornuftigt.': 'Optional — helps Ava split the money sensibly.',
  'Kun os to': 'Just us two',
  'Under 50': 'Under 50',
  'Nøjsomt': 'Lean',
  'Mellemklasse': 'Mid-range',
  'Rundhåndet': 'Generous',
  'Himlen er grænsen': "Sky's the limit",
  'Vil helst ikke sige': 'Rather not say',
  'Jeres drømmebyllup': 'Your dream wedding',
  'Vælg de stemninger der rammer jer — og beskriv gerne med egne ord. Ava bruger det til briefs og stil.':
    'Pick the moods that fit you — and describe it in your own words. Ava uses it for briefs and style.',
  'Stemning': 'Mood',
  'Vælg gerne flere.': 'Pick as many as you like.',
  'Med egne ord': 'In your own words',
  'Have': 'Garden',
  'Rustik lade': 'Rustic barn',
  'Moderne loft': 'Modern loft',
  'Klassisk balsal': 'Classic ballroom',
  'Strand': 'Beach',
  'Slot / herregård': 'Castle / manor',
  'Intimt': 'Intimate',
  'Boho': 'Boho',
  'Destination': 'Destination',
  'Vi drømmer om et bryllup i en gammel avlsgård med lange borde, levende lys og en varm, afslappet stemning…':
    'We dream of a wedding in an old farmhouse with long tables, candlelight and a warm, relaxed atmosphere…',
  'Giv {name} adgang': 'Give {name} access',
  'din partner': 'your partner',
  'I deler samme plan — ingen duplikerede lister eller beskedkopiering.':
    'You share one plan — no duplicate lists or copy-pasting.',
  '{name}s e-mail': "{name}'s email",
  'Invitation sendt til {email}. {name} får et link til at oprette adgang.':
    'Invitation sent to {email}. {name} gets a link to create access.',
  'eller': 'or',
  'Spring over — invitér {name} senere': 'Skip — invite {name} later',
  'Se jeres plan': 'See your plan',
  'Ava · Arbejdede imens I svarede': 'Ava · Worked while you answered',
  'Jeg har forberedt': "I've prepared",
  'tre ting til jer.': 'three things for you.',
  'Baseret på {guests} gæster nær {location} og jeres stil. Ét klik for at se det hele.':
    'Based on {guests} guests near {location} and your style. One click to see it all.',
  'Tidslinje med {n} milepæle': 'Timeline with {n} milestones',
  'Forankret baglæns fra {date}': 'Anchored backwards from {date}',
  '3 venues fundet nær {location}': '3 venues found near {location}',
  'Matchet på gæstetal, stil og dato': 'Matched on guest count, style and date',
  'Ava har skrevet · Venue-henvendelse': 'Ava wrote · Venue enquiry',
  'Klar til send': 'Ready to send',
  'Til': 'To',
  'Emne': 'Subject',
  'Forespørgsel — bryllup {date}': 'Enquiry — wedding {date}',
  'Gå ind i Kalas': 'Enter Kalas',
  'Se hvad Ava har forberedt': "See what Ava's prepared",
  'Gratis at udforske · I godkender alt før noget sendes':
    'Free to explore · You approve everything before anything is sent',
  'snart': 'soon',

  // Seasons
  'Forår': 'Spring',
  'Sommer': 'Summer',
  'Efterår': 'Fall',
  'Vinter': 'Winter',

  // Onboarding chat transitions
  'Vi er {a} & {b}': 'We are {a} & {b}',
  ' — vi gifter os {date} nær {location}.': ' — getting married {date} near {location}.',
  ' — vi gifter os {date}.': ' — getting married {date}.',
  'Dejligt! Hvor stort tænker I det — og hvad er rammen budgetmæssigt? Bare et pejlemærke, det kan altid justeres.':
    'Lovely! How big are you thinking — and what budget range? Just a ballpark, it can always change.',
  'gæster': 'guests',
  'Et selskab': 'A gathering',
  ', {budget} budget': ', {budget} budget',
  'Godt udgangspunkt. Nu til det sjove: hvad drømmer I om? Vælg de stemninger der rammer jer — og beskriv gerne med egne ord.':
    'Good starting point. Now the fun part: what do you dream of? Pick the moods that fit you — and describe it in your own words.',
  'Stil: {s}': 'Style: {s}',
  'Vi finder stilen undervejs.': "We'll find the style along the way.",
  'Smukt — jeg noterer det til jeres leverandør-briefs og hjemmeside. Planlægger I det to?':
    "Beautiful — I'm noting it for your vendor briefs and website. Are the two of you planning together?",
  '{email} er inviteret som medplanlægger.': '{email} is invited as a co-planner.',
  'Jeg klarer det for nu — inviterer partneren senere.': "I'll handle it for now — invite my partner later.",
  'nær {location}': 'near {location}',
  'i jeres region': 'in your region',
  'Perfekt. Imens I svarede har jeg allerede forberedt jeres tidslinje, fundet tre venues {near} og skrevet den første henvendelse. Klar til at se det?':
    'Perfect. While you answered I already prepared your timeline, found three venues {near} and wrote the first enquiry. Ready to see it?',

  // Aha email
  'Kære {venue},': 'Dear {venue},',
  'Vi er {a} & {b} og planlægger vores bryllup': 'We are {a} & {b} and planning our wedding',
  'Vi er': 'We are',
  '{guests} gæster': '{guests} guests',
  'og søger en venue der afspejler vores stil og stemning.': 'and looking for a venue that reflects our style and mood.',
  'Vi er interesserede i jeres weekendpakke og vil gerne...': "We're interested in your weekend package and would like to...",

  // ── Ava chat ────────────────────────────────────────────────────────
  'Lad os planlægge jeres bryllup': "Let's plan your wedding",
  'Fortæl mig om jeres dag, så går jeg i gang med at finde venues.':
    "Tell me about your day and I'll start finding venues.",
  '● Online · jeres bryllupsplanlægger': '● Online · your wedding planner',
  'Find venues til os': 'Find venues for us',
  'Hvad mangler vi at booke?': "What do we still need to book?",
  'Skriv til fotografer': 'Write to photographers',
  'Vedhæft fil': 'Attach file',
  'Skriv til Ava, {name}…': 'Message Ava, {name}…',
  'du': 'you',
  'Besked til Ava': 'Message to Ava',
  'Send besked': 'Send message',
  '{n} venues lagt på jeres board — se dem': '{n} venues added to your board — see them',
  'Sendt til {sent}': 'Sent to {sent}',
  ', {n} sprunget over': ', {n} skipped',
  ', {n} fejlede': ', {n} failed',
  'Foreslået svar til leverandør': 'Suggested reply to the vendor',
  'Sendt ✓': 'Sent ✓',
  'Afvist': 'Dismissed',
  'Sender…': 'Sending…',
  'Se i indbakke': 'See in inbox',
  'Udkast · henvendelse': 'Draft · enquiry',
  'Ava skriver individuelt til {n} valgte leverandører': 'Ava writes individually to {n} chosen vendors',
  '💌 Invitationstekst': '💌 Invitation wording',
  'Bestil tryk →': 'Order prints →',
  'Kopieret': 'Copied',
  'Kopiér': 'Copy',

  // ── Home ────────────────────────────────────────────────────────────
  'Jeres bryllup': 'Your wedding',
  'Godnat': 'Good night',
  'Godmorgen': 'Good morning',
  'Godformiddag': 'Good morning',
  'Goddag': 'Good day',
  'Godaften': 'Good evening',
  'Ava har gjort klar til jer. {n} svar venter på jeres godkendelse — det tager få minutter.':
    'Ava has things ready for you. {n} reply(ies) await your approval — it takes a few minutes.',
  'Alt er ryddet. Ava arbejder videre i baggrunden og siger til, når der er nyt.':
    "All clear. Ava keeps working in the background and will let you know when there's news.",
  'Dage til brylluppet': 'Days to the wedding',
  'Ting venter på jer': 'Things waiting for you',
  'Tilbud modtaget': 'Quotes received',
  'Kr budget': 'DKK budget',
  'Godkendelseskø · {n}': 'Approval queue · {n}',
  'Godkendelseskø · alt ryddet': 'Approval queue · all clear',
  'Leverandør': 'Vendor',
  'Jeres univers, samlet': 'Your world, gathered',
  'ét sted': 'in one place',
  'Hver gang I gemmer et billede, sender Ava det videre til vendor-briefs og hjemmesidens tema.':
    'Every time you save an image, Ava passes it on to vendor briefs and your website theme.',
  'Åbn': 'Open',
  'Ava anbefaler nu': 'Ava recommends now',
  'Alt er klaret for nu. Nyd roen — jeg siger til, når næste skridt nærmer sig.':
    "Everything's handled for now. Enjoy the calm — I'll let you know when the next step nears.",
  '{n} svar klar til godkendelse': '{n} replies ready to approve',
  'Ava har forberedt svar til jeres leverandører': 'Ava has prepared replies to your vendors',
  'Alt er booket — hvor er I dygtige. 🤍': "Everything's booked — well done. 🤍",
  'Jeres hjemmeside (kommer snart)': 'Your website (coming soon)',
  '{who} venter på linket': '{who} awaiting the link',
  'Gæstelisten': 'The guest list',
  'Kopieret!': 'Copied!',
  'Kopiér link': 'Copy link',
  'Tilpas →': 'Customize →',
  'Svar til {vendor}': 'Reply to {vendor}',
  'Ava har skrevet et svar': 'Ava wrote a reply',
  '{vendor} har svaret på jeres henvendelse. Godkend Avas svar, så sender hun det fra Kalas-postkassen — eller tal med hende om det først.':
    "{vendor} replied to your enquiry. Approve Ava's reply and she'll send it from the Kalas mailbox — or talk to her about it first.",
  'Udkast · Ava': 'Draft · Ava',
  'Klar': 'Ready',
  'Vis mindre': 'Show less',
  'Vis hele svaret': 'Show full reply',

  // ── Public wedding site (/w/[slug]) ─────────────────────────────────
  'Historie': 'Story',
  'Program': 'Schedule',
  'Gaveønsker': 'Gifts',
  'dage til': 'days to go',
  'Svar på invitation': 'RSVP',
  'Vores historie': 'Our story',
  'Program for dagen': 'Schedule for the day',
  'Galleri': 'Gallery',
  'Se hos {store}': 'View at {store}',
  'butik': 'store',
  'Reservér gave': 'Reserve gift',
  'Reserveret': 'Reserved',
  'Se ønskelisten': 'See the registry',
  'Transport': 'Transport',
  'Dresscode': 'Dress code',
  'Overnatning': 'Accommodation',
  'FAQ': 'FAQ',
  'Svar venligst inden {date}.': 'Please respond by {date}.',
  'Vi glæder os til at fejre dagen med jer.': "We can't wait to celebrate with you.",
  'RSVP': 'RSVP',
  'Lavet med': 'Made with',
  // RSVP + claim + gate modals
  'Privat side': 'Private page',
  'Indtast koden fra jeres invitation.': 'Enter the code from your invitation.',
  'Adgangskode': 'Password',
  'Forkert kode — prøv igen.': 'Wrong code — try again.',
  'Åbner…': 'Opening…',
  'Se siden': 'View the page',
  'Tak — vi ses!': 'Thanks — see you there!',
  'Tak for svaret': 'Thanks for responding',
  'Vi har noteret jeres deltagelse.': "We've noted that you're coming.",
  'Vi kommer til at savne jer.': "We'll miss you.",
  'Navn': 'Name',
  'E-mail (valgfrit)': 'Email (optional)',
  'Kommer I?': 'Are you coming?',
  'Ja, vi kommer 🎉': "Yes, we'll be there 🎉",
  'Desværre ikke': "Sorry, can't make it",
  'Jeg tager en ledsager med': "I'm bringing a plus-one",
  'Ledsagers navn': "Plus-one's name",
  'Menuvalg (valgfrit)': 'Meal choice (optional)',
  'f.eks. kød, fisk, vegetar': 'e.g. meat, fish, vegetarian',
  'Allergier / hensyn (valgfrit)': 'Allergies / needs (optional)',
  'Besked til brudeparret (valgfrit)': 'Message to the couple (optional)',
  'Noget gik galt — prøv igen.': 'Something went wrong — try again.',
  'Send svar': 'Send response',
  'Tak — gaven er reserveret': 'Thanks — the gift is reserved',
  'Brudeparret får besked. De ved ikke hvem, før dagen.': "The couple is notified. They won't know who until the day.",
  'Hilsen (valgfrit)': 'Message (optional)',
  'Denne gave er allerede reserveret.': 'This gift is already reserved.',
  'Reserverer…': 'Reserving…',
  'Reservér': 'Reserve',

  // ── Registry (Ønskeliste) screen ────────────────────────────────────
  'Gaver, I faktisk': 'Gifts you actually',
  'ønsker jer': 'want',
  'Indsæt et link til en gave, så henter vi billede og pris. Gæsterne kan reservere den fra jeres bryllupsside — så to ikke køber det samme.':
    "Paste a link to a gift and we'll pull the image and price. Guests can reserve it from your wedding site — so two people don't buy the same thing.",
  'Indsæt produktlink (fx fra en webshop)…': 'Paste a product link (e.g. from a web shop)…',
  'Henter…': 'Fetching…',
  'Gavens navn': 'Gift name',
  'Pris': 'Price',
  'Butik': 'Store',
  'Gem på listen': 'Save to list',
  'Ingen ønsker endnu': 'No wishes yet',
  'Indsæt jeres første gavelink ovenfor.': 'Paste your first gift link above.',
  '{n}/{q} reserveret': '{n}/{q} reserved',
  'Se produkt ↗': 'View product ↗',
  'Ønskelisten vises automatisk på jeres bryllupsside under “Gaveønsker”.':
    'The registry shows automatically on your wedding site under “Gifts”.',
  'Åbn hjemmeside': 'Open website',

  // ── Onboarding stepper (globe flow) ─────────────────────────────────
  'Trin {a} af {b}': 'Step {a} of {b}',
  'Jeres historie': 'Your story',
  'Datoen': 'The date',
  'Omfang': 'Scope',
  'Partner': 'Partner',
  'En omtænksom start': 'A thoughtful beginning',
  'Lad os gøre det til jeres.': "Let's make this feel like yours.",
  'Seks korte trin hjælper Ava med at skræddersy venues, opgaver og anbefalinger til jeres bryllup.':
    'Six short steps help Ava tailor every venue, task, and recommendation to your celebration.',
  'Anbefalinger formet omkring jer': 'Recommendations shaped around you',
  'Ændr ethvert svar senere': 'Change any answer later',
  'Velkommen til Kalas': 'Welcome to Kalas',
  'Hvem skal': "Who's getting",
  'giftes?': 'married?',
  'Fortæl os hvad vi skal kalde jer begge. Ava bruger fornavne, så planlægningen føles personlig fra første skridt.':
    'Tell us what to call you both. Ava uses first names to make planning feel personal from the very first step.',
  'Dit fornavn': 'Your first name',
  'Partners fornavn': "Partner's first name",
  'f.eks. Maya': 'e.g. Maya',
  'f.eks. Elias': 'e.g. Elias',
  'Bruges kun til at personliggøre jeres planlægningsrum.': 'Only used to personalize your planning space.',
  'Ca. 3 minutter at gennemføre': 'About 3 minutes to complete',
  'Jeres svar gemmes undervejs.': 'Your answers are saved as you go.',
  'Fortsæt': 'Continue',
  'Hvor i verden?': 'Where in the world?',
  'En sæson, en dato eller “vi ved det ikke endnu” — Ava tilpasser sig.':
    'A season, a date, or “we’re not sure yet” — Ava adapts.',
  'Hvor mange gæster?': 'How many guests?',
  'Et pejlemærke er nok — Ava bruger det til venues, budget og tidslinje.':
    'A ballpark is enough — Ava uses it for venues, budget and timeline.',
  'Hvad føles som jer?': 'What feels like you?',
  'Vælg det der frister — Ava lærer jeres æstetik at kende.':
    'Pick what appeals — Ava learns your aesthetic.',
  'Giv partneren adgang': 'Give your partner access',
  'Hvornår siger I ja?': 'When do you say I do?',
  'Så Ava kan hilse på jer som mennesker — ikke et regneark.': 'So Ava can greet you like people — not a spreadsheet.',
  'Hvor i': 'Where in',
  'verden?': 'the world?',
  'Drej på kloden og vælg et sted der frister — hjemme eller langt væk.':
    'Spin the globe and pick somewhere tempting — close to home or far away.',
  'Drej på kloden og vælg et sted': 'Spin the globe and pick a place',
  'Intet valgt endnu — prøv at trykke på en prik.': 'Nothing picked yet — try tapping a dot.',
  'Drej på kloden, zoom ind og tryk på et land': 'Spin the globe, zoom in and tap a country',
  'Drej og zoom på kloden, og tryk på et land — så henter vi de største byer og smukkeste bryllupsdestinationer.':
    "Spin and zoom the globe, then tap a country — we'll fetch its top cities and loveliest wedding destinations.",
  'Intet valgt endnu — tryk på et land og vælg et sted.': 'Nothing chosen yet — tap a country and pick a place.',
  '{n} gemt til senere': '{n} saved for later',
  'Finder de smukkeste steder…': 'Finding the loveliest places…',
  'Vi kunne ikke hente forslag lige nu.': "We couldn't load suggestions right now.",
  'Prøv igen': 'Try again',
  'Ava finder venues til jer…': 'Ava is finding venues for you…',
  'Baseret på {location}, {guests} gæster og jeres gemte steder.': 'Based on {location}, {guests} guests and your saved places.',
  'Kunne ikke hente venues lige nu': "Couldn't load venues right now",
  'I kan fortsætte — Ava finder steder i appen bagefter.': 'You can continue — Ava will find venues in the app later.',
  'Swipe jeres drømmevenues': 'Swipe your dream venues',
  'Højre for ja, venstre for nej — Ava lærer jeres smag af swipes.': 'Right for yes, left for no — Ava learns your taste from swipes.',
  '{n} venues gemt': '{n} venues saved',
  'Ava bruger jeres valg til at finpudse forslag i Kalas.': 'Ava uses your picks to refine suggestions in Kalas.',
  'Ja': 'Yes',
  'Nej': 'No',
  'anmeldelser': 'reviews',
  'Find jeres stil gennem steder.': 'Find your style through places.',
  'Swipe rigtige venues — Ava lærer hvad der føles som jer.': 'Swipe real venues — Ava learns what feels like you.',
  'Søg på Google': 'Search on Google',
  'Bryllupsdestinationer': 'Wedding destinations',
  'Ingen forslag for dette land endnu.': 'No suggestions for this country yet.',
  'Hjerter gemmes, så Ava kan finde leverandører dér senere.':
    'Hearts are saved so Ava can find vendors there later.',
  'Valgt som jeres sted': 'Chosen as your place',
  'Fjern fra gemte': 'Remove from saved',
  'Gem til senere': 'Save for later',
  'Skriv selv': 'Write your own',
  'Tilbage til kloden': 'Back to the globe',
  'Eller skriv jeres eget sted': 'Or type your own place',
  'f.eks. Odense · Sydfyn · jeres sommerhusby': 'e.g. Odense · South Funen · your summer-house town',
  'Hvornår': 'When',
  'Hvornår siger I': 'When do you say',
  'ja?': 'I do?',
  'Rammen': 'The frame',
  'Stilen': 'The style',
  'Sammen om det': 'In it together',
  'I deler samme plan — ingen duplikerede lister eller beskedkopiering. Valgfrit.':
    "You share one plan — no duplicate lists or copy-pasting. Optional.",
  'Indlæser kloden…': 'Loading the globe…',

  // Destination labels (source Danish → English)
  'København': 'Copenhagen',
  'Toscana': 'Tuscany',
  'Amalfikysten': 'Amalfi Coast',
  'Comosøen': 'Lake Como',
  'Lissabon': 'Lisbon',
  'Alperne': 'The Alps',
  'Skotland': 'Scotland',
  'Island': 'Iceland',
  'Fyn': 'Funen',
  // Countries
  'Danmark': 'Denmark',
  'Sverige': 'Sweden',
  'Storbritannien': 'United Kingdom',
  'Frankrig': 'France',
  'Italien': 'Italy',
  'Grækenland': 'Greece',
  'Spanien': 'Spain',
  'Portugal': 'Portugal',
  'Kroatien': 'Croatia',
  'Østrig': 'Austria',
  'Marokko': 'Morocco',
  'Mexico': 'Mexico',
  'Sydafrika': 'South Africa',
  'Indonesien': 'Indonesia',
  'Japan': 'Japan',
  'USA': 'USA',

  // ── Guided tour ─────────────────────────────────────────────────────
  'Spring over': 'Skip',
  'Kom i gang': 'Get started',
  'Rundvisning': 'Tour',
  'Jeres overblik': 'Your overview',
  'Alt der venter på et svar samles her — godkend, afvis eller spørg Ava til råds.':
    'Everything waiting on an answer gathers here — approve, decline or ask Ava for advice.',
  'Planen, i rækkefølge': 'The plan, in order',
  'Ava sekvenserer opgaverne baglæns fra jeres dato, så I altid kender næste skridt.':
    'Ava sequences the tasks backwards from your date, so you always know the next step.',
  'Find jeres stil': 'Find your style',
  'Swipe billeder I elsker — Ava former venues og leverandører efter jeres æstetik.':
    'Swipe photos you love — Ava shapes venues and vendors around your aesthetic.',
  'Jeres drømmested': 'Your dream place',
  'Swipe eller fortæl Ava hvad I drømmer om — så finder hun rigtige steder med priser.':
    'Swipe or tell Ava what you dream of — she’ll find real places with prices.',
  'Hele holdet': 'The whole team',
  'Fotograf, blomster, musik og mere — Ava kontakter dem med jeres brief.':
    'Photographer, flowers, music and more — Ava contacts them with your brief.',
  'Styr på pengene': 'Money under control',
  'Ava fordeler budgettet og siger til, før I rammer loftet.':
    'Ava splits the budget and warns you before you hit the ceiling.',
  'Tilføj gæster, og lad Ava sende invitationer og holde styr på RSVP.':
    'Add guests and let Ava send invitations and keep track of RSVPs.',
  'Jeres bryllupsside': 'Your wedding site',
  'Vælg et tema og publicér på minutter — navne, dato og billeder er klar.':
    'Pick a theme and publish in minutes — names, date and photos are ready.',
  'Send invitationerne': 'Send the invitations',
  'Ava skriver ordlyden, I godkender — digitalt eller som fysisk tryk.':
    'Ava writes the wording, you approve — digital or physical print.',
  'Byg jeres ønskeliste': 'Build your registry',
  'Saml ønsker fra hele nettet — gæsterne reserverer med ét klik.':
    'Collect wishes from across the web — guests reserve with one click.',
};
