/* Danish → English dictionary. Danish is the source language of the app, so
   the Danish string is the lookup key; a missing entry falls back to Danish.
   Use {name} placeholders for interpolation via t(str, { name }). */

export const EN: Record<string, string> = {
  // ── Navigation ──────────────────────────────────────────────────────
  'Hjem': 'Home',
  'Ava': 'Ava',
  'Inspiration': 'Inspiration',
  'Venues': 'Venues',
  'Leverandører': 'Vendors',
  'Henvendelser': 'Inbox',
  'Budget': 'Budget',
  'Gæster': 'Guests',
  'Hjemmeside': 'Website',
  'Invitationer': 'Invitations',
  'Tidslinje': 'Timeline',
  'Bordplan': 'Seating',
  'Alle sider': 'All pages',
  'Flere sider': 'More pages',
  'Indstillinger': 'Settings',
  'Luk': 'Close',
  'Planlægning': 'Planning',
  '{n} dage tilbage': '{n} days left',
  'Tal med Ava — {n} nye beskeder': 'Talk to Ava — {n} new messages',

  // ── Common verbs / chrome ───────────────────────────────────────────
  'Tilbage': 'Back',
  'Næste': 'Next',
  'Videre': 'Continue',
  'Gem': 'Save',
  'Gemt': 'Saved',
  'Annuller': 'Cancel',
  'Tilføj': 'Add',
  'Fjern': 'Remove',
  'Slet': 'Delete',
  'Send': 'Send',
  'Sendt': 'Sent',
  'Godkend & send': 'Approve & send',
  'Afvis': 'Dismiss',
  'Generér igen': 'Regenerate',
  'Importér': 'Import',
  'Tal med Ava': 'Talk to Ava',
  'Spørg Ava': 'Ask Ava',
  'Se venues der matcher': 'See matching venues',
  'kommer snart': 'coming soon',
  'Sprog': 'Language',
  'Dansk': 'Danish',
  'Engelsk': 'English',

  // ── Onboarding ──────────────────────────────────────────────────────
  'Hej! Jeg er Ava — din personlige bryllupsassistent. Lad os starte med det vigtigste: hvem er I, og hvornår er den store dag?':
    "Hi! I'm Ava — your personal wedding assistant. Let's start with the essentials: who are you, and when is the big day?",
  'Planlagt med ro — af Ava, godkendt af jer.': 'Planned calmly — by Ava, approved by you.',
  'Fortæl om': 'Tell us about the',
  'brylluppet': 'wedding',
  'Ingen konto nødvendig — I kan altid ændre det undervejs.': 'No account needed — you can always change it later.',
  'Dit navn': 'Your name',
  'Partners navn': "Partner's name",
  'Fornavn': 'First name',
  'Lokation': 'Location',
  'Hjemland eller udland — skriv hvad I drømmer om.': 'Home or abroad — write whatever you dream of.',
  'f.eks. nær København · Toscana · Sydfrankrig': 'e.g. near Copenhagen · Tuscany · South of France',
  'Hvornår?': 'When?',
  'En sæson er fint — I behøver ikke en præcis dato endnu.': "A season is fine — you don't need an exact date yet.",
  'Præcis dato': 'Exact date',
  'Ved ikke endnu': 'Not sure yet',
  'Det lyder godt': 'Sounds good',
  'Hvor stort': 'How big are',
  'tænker I?': 'you thinking?',
  'Bare et pejlemærke — Ava bruger det til at forme venues, budget og tidslinje.':
    'Just a ballpark — Ava uses it to shape venues, budget and timeline.',
  'Antal gæster': 'Number of guests',
  'Valgfrit — hjælper Ava med at fordele pengene fornuftigt.': 'Optional — helps Ava split the money sensibly.',
  'Kun os to': 'Just us two',
  'Under 50': 'Under 50',
  'Nøjsomt': 'Lean',
  'Mellemklasse': 'Mid-range',
  'Rundhåndet': 'Generous',
  'Himlen er grænsen': "Sky's the limit",
  'Vil helst ikke sige': 'Rather not say',
  'Jeres drømmebyllup': 'Your dream wedding',
  'Vælg de stemninger der rammer jer — og beskriv gerne med egne ord. Ava bruger det til briefs og stil.':
    'Pick the moods that fit you — and describe it in your own words. Ava uses it for briefs and style.',
  'Stemning': 'Mood',
  'Vælg gerne flere.': 'Pick as many as you like.',
  'Med egne ord': 'In your own words',
  'Have': 'Garden',
  'Rustik lade': 'Rustic barn',
  'Moderne loft': 'Modern loft',
  'Klassisk balsal': 'Classic ballroom',
  'Strand': 'Beach',
  'Slot / herregård': 'Castle / manor',
  'Intimt': 'Intimate',
  'Boho': 'Boho',
  'Destination': 'Destination',
  'Vi drømmer om et bryllup i en gammel avlsgård med lange borde, levende lys og en varm, afslappet stemning…':
    'We dream of a wedding in an old farmhouse with long tables, candlelight and a warm, relaxed atmosphere…',
  'Giv {name} adgang': 'Give {name} access',
  'din partner': 'your partner',
  'I deler samme plan — ingen duplikerede lister eller beskedkopiering.':
    'You share one plan — no duplicate lists or copy-pasting.',
  '{name}s e-mail': "{name}'s email",
  'Invitation sendt til {email}. {name} får et link til at oprette adgang.':
    'Invitation sent to {email}. {name} gets a link to create access.',
  'eller': 'or',
  'Spring over — invitér {name} senere': 'Skip — invite {name} later',
  'Se jeres plan': 'See your plan',
  'Ava · Arbejdede imens I svarede': 'Ava · Worked while you answered',
  'Jeg har forberedt': "I've prepared",
  'tre ting til jer.': 'three things for you.',
  'Baseret på {guests} gæster nær {location} og jeres stil. Ét klik for at se det hele.':
    'Based on {guests} guests near {location} and your style. One click to see it all.',
  'Tidslinje med {n} milepæle': 'Timeline with {n} milestones',
  'Forankret baglæns fra {date}': 'Anchored backwards from {date}',
  '3 venues fundet nær {location}': '3 venues found near {location}',
  'Matchet på gæstetal, stil og dato': 'Matched on guest count, style and date',
  'Ava har skrevet · Venue-henvendelse': 'Ava wrote · Venue enquiry',
  'Klar til send': 'Ready to send',
  'Til': 'To',
  'Emne': 'Subject',
  'Forespørgsel — bryllup {date}': 'Enquiry — wedding {date}',
  'Gå ind i Kalas': 'Enter Kalas',
  'Se hvad Ava har forberedt': "See what Ava's prepared",
  'Gratis at udforske · I godkender alt før noget sendes':
    'Free to explore · You approve everything before anything is sent',
  'snart': 'soon',

  // Seasons
  'Forår': 'Spring',
  'Sommer': 'Summer',
  'Efterår': 'Fall',
  'Vinter': 'Winter',

  // Onboarding chat transitions
  'Vi er {a} & {b}': 'We are {a} & {b}',
  ' — vi gifter os {date} nær {location}.': ' — getting married {date} near {location}.',
  ' — vi gifter os {date}.': ' — getting married {date}.',
  'Dejligt! Hvor stort tænker I det — og hvad er rammen budgetmæssigt? Bare et pejlemærke, det kan altid justeres.':
    'Lovely! How big are you thinking — and what budget range? Just a ballpark, it can always change.',
  'gæster': 'guests',
  'Et selskab': 'A gathering',
  ', {budget} budget': ', {budget} budget',
  'Godt udgangspunkt. Nu til det sjove: hvad drømmer I om? Vælg de stemninger der rammer jer — og beskriv gerne med egne ord.':
    'Good starting point. Now the fun part: what do you dream of? Pick the moods that fit you — and describe it in your own words.',
  'Stil: {s}': 'Style: {s}',
  'Vi finder stilen undervejs.': "We'll find the style along the way.",
  'Smukt — jeg noterer det til jeres leverandør-briefs og hjemmeside. Planlægger I det to?':
    "Beautiful — I'm noting it for your vendor briefs and website. Are the two of you planning together?",
  '{email} er inviteret som medplanlægger.': '{email} is invited as a co-planner.',
  'Jeg klarer det for nu — inviterer partneren senere.': "I'll handle it for now — invite my partner later.",
  'nær {location}': 'near {location}',
  'i jeres region': 'in your region',
  'Perfekt. Imens I svarede har jeg allerede forberedt jeres tidslinje, fundet tre venues {near} og skrevet den første henvendelse. Klar til at se det?':
    'Perfect. While you answered I already prepared your timeline, found three venues {near} and wrote the first enquiry. Ready to see it?',

  // Aha email
  'Kære {venue},': 'Dear {venue},',
  'Vi er {a} & {b} og planlægger vores bryllup': 'We are {a} & {b} and planning our wedding',
  'Vi er': 'We are',
  '{guests} gæster': '{guests} guests',
  'og søger en venue der afspejler vores stil og stemning.': 'and looking for a venue that reflects our style and mood.',
  'Vi er interesserede i jeres weekendpakke og vil gerne...': "We're interested in your weekend package and would like to...",

  // ── Ava chat ────────────────────────────────────────────────────────
  'Lad os planlægge jeres bryllup': "Let's plan your wedding",
  'Fortæl mig om jeres dag, så går jeg i gang med at finde venues.':
    "Tell me about your day and I'll start finding venues.",
  '● Online · jeres bryllupsplanlægger': '● Online · your wedding planner',
  'Find venues til os': 'Find venues for us',
  'Hvad mangler vi at booke?': "What do we still need to book?",
  'Skriv til fotografer': 'Write to photographers',
  'Vedhæft fil': 'Attach file',
  'Skriv til Ava, {name}…': 'Message Ava, {name}…',
  'du': 'you',
  'Besked til Ava': 'Message to Ava',
  'Send besked': 'Send message',
  '{n} venues lagt på jeres board — se dem': '{n} venues added to your board — see them',
  'Sendt til {sent}': 'Sent to {sent}',
  ', {n} sprunget over': ', {n} skipped',
  ', {n} fejlede': ', {n} failed',
  'Foreslået svar til leverandør': 'Suggested reply to the vendor',
  'Sendt ✓': 'Sent ✓',
  'Afvist': 'Dismissed',
  'Sender…': 'Sending…',
  'Se i indbakke': 'See in inbox',
  'Udkast · henvendelse': 'Draft · enquiry',
  'Ava skriver individuelt til {n} valgte leverandører': 'Ava writes individually to {n} chosen vendors',
  '💌 Invitationstekst': '💌 Invitation wording',
  'Bestil tryk →': 'Order prints →',
  'Kopieret': 'Copied',
  'Kopiér': 'Copy',

  // ── Home ────────────────────────────────────────────────────────────
  'Jeres bryllup': 'Your wedding',
  'Godnat': 'Good night',
  'Godmorgen': 'Good morning',
  'Godformiddag': 'Good morning',
  'Goddag': 'Good day',
  'Godaften': 'Good evening',
  'Ava har gjort klar til jer. {n} svar venter på jeres godkendelse — det tager få minutter.':
    'Ava has things ready for you. {n} reply(ies) await your approval — it takes a few minutes.',
  'Alt er ryddet. Ava arbejder videre i baggrunden og siger til, når der er nyt.':
    "All clear. Ava keeps working in the background and will let you know when there's news.",
  'Dage til brylluppet': 'Days to the wedding',
  'Ting venter på jer': 'Things waiting for you',
  'Tilbud modtaget': 'Quotes received',
  'Kr budget': 'DKK budget',
  'Godkendelseskø · {n}': 'Approval queue · {n}',
  'Godkendelseskø · alt ryddet': 'Approval queue · all clear',
  'Leverandør': 'Vendor',
  'Jeres univers, samlet': 'Your world, gathered',
  'ét sted': 'in one place',
  'Hver gang I gemmer et billede, sender Ava det videre til vendor-briefs og hjemmesidens tema.':
    'Every time you save an image, Ava passes it on to vendor briefs and your website theme.',
  'Åbn': 'Open',
  'Ava anbefaler nu': 'Ava recommends now',
  'Alt er klaret for nu. Nyd roen — jeg siger til, når næste skridt nærmer sig.':
    "Everything's handled for now. Enjoy the calm — I'll let you know when the next step nears.",
  '{n} svar klar til godkendelse': '{n} replies ready to approve',
  'Ava har forberedt svar til jeres leverandører': 'Ava has prepared replies to your vendors',
  'Alt er booket — hvor er I dygtige. 🤍': "Everything's booked — well done. 🤍",
  'Jeres hjemmeside (kommer snart)': 'Your website (coming soon)',
  '{who} venter på linket': '{who} awaiting the link',
  'Gæstelisten': 'The guest list',
  'Kopieret!': 'Copied!',
  'Kopiér link': 'Copy link',
  'Tilpas →': 'Customize →',
  'Svar til {vendor}': 'Reply to {vendor}',
  'Ava har skrevet et svar': 'Ava wrote a reply',
  '{vendor} har svaret på jeres henvendelse. Godkend Avas svar, så sender hun det fra Kalas-postkassen — eller tal med hende om det først.':
    "{vendor} replied to your enquiry. Approve Ava's reply and she'll send it from the Kalas mailbox — or talk to her about it first.",
  'Udkast · Ava': 'Draft · Ava',
  'Klar': 'Ready',
  'Vis mindre': 'Show less',
  'Vis hele svaret': 'Show full reply',

  // ── Dashboard ───────────────────────────────────────────────────────
  'Det grundlæggende': 'The basics',
  'Sted og cirka antal gæster låser venue-jagten op': 'Location and a rough guest count unlock the venue hunt',
  'Find jeres venue': 'Find your venue',
  'Alt det lokale udspringer af, hvor I siger ja': "Everything local flows from where you say 'I do'",
  'Låses op, når det grundlæggende er på plads': 'Unlocks once the basics are in',
  'Book leverandørerne': 'Book the vendors',
  'Blomster, foto, musik og mad — tæt på jeres venue': 'Flowers, photos, music and catering — all local to your venue',
  'Låses op, når I har valgt venue': "Unlocks when you've chosen a venue",
  'Send invitationerne': 'Send the invites',
  'Design, formulér og bestil jeres invitationer': 'Design, word and order your invitations',
  'Låses op, når venue og dato er på plads': 'Unlocks after venue and date',
  '{n} tilbud er inde — sammenlign og vælg': '{n} quotes in — compare and choose',
  '{n} venues på jeres shortliste': '{n} venues on your shortlist',
  '{n} ulæste svar i indbakken': '{n} unread replies in the inbox',
  'Nye beskeder fra jeres leverandører': 'New messages from your vendors',
  '{n} opgaver er over tid': '{n} tasks are overdue',
  'Et lille skub, så er I foran igen': "A small push and you're ahead again",
  'Bryllupsdato': 'Wedding date',
  'Dato ikke fastsat': 'Date not set',
  'Tillykke!': 'Congratulations!',
  'Brylluppet er holdt': 'The wedding has happened',
  'Dage til brylluppet · ca.': 'Days to the wedding · approx.',
  'Gæster har sagt ja': 'Guests said yes',
  'Gæsteliste': 'Guest list',
  'Budget disponeret': 'Budget allocated',
  'Kr planlagt': 'DKK planned',
  'Venue-jagten': 'The venue hunt',
  'Åbn venues': 'Open venues',
  'Venue-jagten venter på jer': 'The venue hunt awaits you',
  'Swipe jer gennem steder, der matcher jeres stil — Ava kontakter dem, I kan lide.':
    'Swipe through places that match your style — Ava contacts the ones you like.',
  'Start venue-jagten': 'Start the venue hunt',
  'Shortlistet': 'Shortlisted',
  'Kontaktet': 'Contacted',
  'Tilbud': 'Quotes',
  'Booket': 'Booked',
  'Bedste tilbud': 'Best quote',
  'Opgaver · {n} over tid': 'Tasks · {n} overdue',
  'Opgaver · de næste 14 dage': 'Tasks · the next 14 days',
  'Se tidslinjen': 'See the timeline',
  'Ingen opgaver de næste 14 dage — I er foran. 🤍': "No tasks in the next 14 days — you're ahead. 🤍",
  'Markér som klaret': 'Mark as done',
  'Over tid': 'Overdue',
  'Seneste aktivitet': 'Recent activity',
  'Tilbud fra {venue}': 'Quote from {venue}',
  'Nyt svar fra {venue}': 'New reply from {venue}',
  'Forespørgsel sendt til {venue}': 'Inquiry sent to {venue}',
  'Ava har skrevet et udkast til {venue}': 'Ava drafted a reply to {venue}',
  'Nyt billede på moodboardet': 'New image on the moodboard',
  'Byg jeres moodboard': 'Build your moodboard',
  'Moodboard-billede': 'Moodboard image',
  'Jeres hjemmeside': 'Your website',
  'Del detaljer, program og RSVP med gæsterne': 'Share details, schedule and RSVP with your guests',
  'Kommer snart': 'Coming soon',
  'Skal vi begynde?': 'Shall we begin?',
  'Fortæl Ava om jeres bryllup — sted, gæster og drømme — så bygger hun planen op omkring jer.':
    'Tell Ava about your wedding — place, guests and dreams — and she builds the plan around you.',
};
